### ISSUE TITLE
Compare to Joan's checklist

### ISSUE THREAD

**Issue by korenmiklos** [REStud/guidance#7]
https://static.primary.prod.gcms.the-infra.com/static/site/ej/document/Checklist_for_authors_July2020.pdf?node=d63a8d83ba1a1421c6f1&version=263849:ae02e800bfdafd0dbf0f

**Comment by korenmiklos** [comment]
https://github.com/REStud/guidance/blob/main/RRS/Reproducible-Research-Standard-1.0.md

**Comment by korenmiklos** [comment]
- 13b
- 13c
- 12b
- 12c
- 11e "For EJ, running time is required."
- 11g
- 5
- 3
- 2a
- 4a
- 8a
- 8c
- 1

# Extra
- expected runtime
- synthetic data
- IRB approval

# Missing
- 8b

**Comment by csokaimola** [comment]
What is the difference between 8b and 8c?
